# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: "radix-default-backend"

image:
  repository: ghcr.io/equinor/radix-ingress-default-backend
  tag: ""
  pullPolicy: Always

# Annotations to add to the Deployment
deploymentAnnotations: {}
# Extra pod labels
podLabels: {}

logLevel: "info"
logPretty: "False"
port: "8000"
errorFilesPath: "/www"
defaultResponseFormat: "text/html"

resources:
  limits:
    cpu: 50m
    memory: 50Mi
  requests:
    cpu: 50m
    memory: 50Mi

# Affinity for pod scheduling
affinity: {}

# Node selector for pod scheduling
nodeSelector: {}

# Tolerations for pod scheduling
tolerations: []
